'use strict';function _interopDefault(a){return a&&"object"===typeof a&&"default"in a?a["default"]:a}var Color=_interopDefault(require("@lost-types/color")),mathx=require("@lost-types/mathx"),Range=_interopDefault(require("@lost-types/range")),alphaRange=new Range(1);
function mix(a,b){var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1;if(arguments.length){if(!b)return new Color(a);if(!a)return new Color(b);var d=a instanceof Color?a:new Color(a),e=b instanceof Color?b:new Color(b),f=alphaRange.clamp(mathx.round(d.alpha*c,4));c=mathx.round(e.red+f*(d.red-e.red),0);var g=mathx.round(e.green+f*(d.green-e.green),0);d=mathx.round(e.blue+f*(d.blue-e.blue),0);return new Color([c,g,d])}}
function contrast(a,b){if(arguments.length){if(!a||!b)return 1;var c=a instanceof Color?a:new Color(a),d=b instanceof Color?b:new Color(b);1>c.alpha&&(c=mix(c,d));return mathx.round((Math.max(c.luminance,d.luminance)+.05)/(Math.min(c.luminance,d.luminance)+.05),2)}}
function findByContrast(a,b,c,d){c=c instanceof Color?c:new Color(c);for(var e=0,f=1,g,h,k=0;7>=k;){g=new Color({hue:a,saturation:b,lightness:mathx.round((f+e)/2,2)});h=contrast(g,c);if(mathx.approx(h,d,.05))break;h>d&&g.luminance>c.luminance||h<d&&g.luminance<c.luminance?f=(f+e)/2:e=(f+e)/2;k+=1}return g}function getTone(a){a=a instanceof Color?a:new Color(a);return.5===a.lightness?a:new Color({hue:a.hue,saturation:a.saturation,lightness:.5})}
function invert(a){a=a instanceof Color?a:new Color(a);return new Color([255-a.red,255-a.green,255-a.blue,a.alpha])}function hueShift(a,b){a=a instanceof Color?a:new Color(a);if(0===mathx.modulo(b,360))return a;b={hue:mathx.modulo(a.hue+b,360),saturation:a.saturation,lightness:a.lightness,alpha:a.alpha};return new Color(b)}function opposite(a){return hueShift(a,180)}
function getHueByOffset(a){if(arguments.length)return mathx.modulo(30*a-45+(1<arguments.length&&void 0!==arguments[1]?arguments[1]:0),360)}function offsetHue(a,b){a=a instanceof Color?a:new Color(a);if(a.hueGroupOffset===b)return a;b={hue:getHueByOffset(a.hueGroup,b),saturation:a.saturation,lightness:a.lightness,alpha:a.alpha};return new Color(b)}
function randomRgbColor(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[0,255],b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[0,255],c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:[0,255];a=Array.isArray(a)?mathx.random(a,0):a;b=Array.isArray(b)?mathx.random(b,0):b;c=Array.isArray(c)?mathx.random(c,0):c;return new Color([a,b,c])}
function randomHslColor(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[0,359],b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[0,1],c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:[0,1];a=Array.isArray(a)?mathx.random(a,0):+a;b=Array.isArray(b)?mathx.random(b,2):+b;c=Array.isArray(c)?mathx.random(c,2):+c;return new Color({hue:a,saturation:b,lightness:c})}
function randomByContrast(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:4.5,b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[255,255,255],c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:[0,1],d=mathx.random([0,359],0);c=Array.isArray(c)?mathx.random(c,2):+c;return findByContrast(d,c,b,a)}var filterRange=new Range(.5),WARM_FILTER=[247,166,115],COLD_FILTER=[67,162,237];
function warmer(a){var b=2<arguments.length&&void 0!==arguments[2]?arguments[2]:WARM_FILTER,c=filterRange.clamp(mathx.round((1<arguments.length&&void 0!==arguments[1]?arguments[1]:.2)/10,2));return mix(b,a,c)}function cooler(a){var b=2<arguments.length&&void 0!==arguments[2]?arguments[2]:COLD_FILTER,c=filterRange.clamp(mathx.round((1<arguments.length&&void 0!==arguments[1]?arguments[1]:.2)/10,2));return mix(b,a,c)}
var Colorista={contrast,cooler,getHueByOffset,getTone,findByContrast,hueShift,invert,mix,offsetHue,opposite,randomByContrast,randomHslColor,randomRgbColor,warmer};module.exports=Colorista
